

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";



CREATE TABLE `BD_IMAGENS` (
  `ID` int(11) NOT NULL,
  `SRC` varchar(45) NOT NULL,
  `Nome` varchar(45) NOT NULL,
  `TAG` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



INSERT INTO `BD_IMAGENS` (`ID`, `SRC`, `Nome`, `TAG`) VALUES
(3, './Img_Strg/Group 14 (1).png', 'Microscópio Óptico Esquema', 'Esquema');



ALTER TABLE `BD_IMAGENS`
  ADD PRIMARY KEY (`ID`);


--
ALTER TABLE `BD_IMAGENS`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

